version: "3.7"
services:
  leapsome_mongodb:
    build: ./mongo
    restart: always
    logging:
      driver: none
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: leapsome-interview
    ports:
      - 27017:27017
